name: ios_test_application
description: iosの挙動確認

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  chopper: ^4.0.6
  chopper_generator: ^4.0.6
  freezed: ^2.0.4
  freezed_annotation: ^2.0.3
  flutter_riverpod: ^1.0.3
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
